### ISSUE TITLE
"in memory panic stackshot succeeded" 

### ISSUE THREAD

**Issue by JavadRabe** [TongDucThanhNam/OptimizeLegion5-15ACH6H#1]
I tried everything and always see "in memory panic stackshot succeeded"
Device: Legion 5, ryzen 5600h + rtx 3050 15ach6
Xhci1 is disabled
IGPU VRAM : 2G/4G
Secure boot and device guard is disabled
Nootedred is removed!
I tried different smbios but not work
What should i do? Change some acpi or anything like that?

**Comment by TongDucThanhNam** [comment]
> I tried everything and always see "in memory panic stackshot succeeded" Device: Legion 5, ryzen 5600h + rtx 3050 15ach6 Xhci1 is disabled IGPU VRAM : 2G/4G Secure boot and device guard is disabled Nootedred is removed! I tried different smbios but not work What should i do? Change some acpi or anything like that?

Hi, I have update respository. You can try EFI from `EFI for installer` to installer it. Btw, have you increase EFI size to 200MB or more(image below) ?
![EFI](https://github.com/TongDucThanhNam/OptimizeLegion5-15ACH6H/assets/96881214/b87f31bc-6a45-4ec1-891e-bcdcca5233fc)

**Comment by JavadRabe** [comment]
> > I tried everything and always see "in memory panic stackshot succeeded" Device: Legion 5, ryzen 5600h + rtx 3050 15ach6 Xhci1 is disabled IGPU VRAM : 2G/4G Secure boot and device guard is disabled Nootedred is removed! I tried different smbios but not work What should i do? Change some acpi or anything like that?
> 
> Hi, I have update respository. You can try EFI from `EFI for installer` to installer it. Btw, have you increase EFI size to 200MB or more(image below) ? ![EFI](https://user-images.githubusercontent.com/96881214/263448905-b87f31bc-6a45-4ec1-891e-bcdcca5233fc.png)

first of all thank you for help!
Yes the EFI partition is 260MB by default , i tried new EFI installer but is there same problem


![photo_2023-08-27_01-42-36](https://github.com/TongDucThanhNam/OptimizeLegion5-15ACH6H/assets/83281947/98ab8f6d-7b4e-4d1d-81ab-3d3c8151ec31)
![image](https://github.com/TongDucThanhNam/OptimizeLegion5-15ACH6H/assets/83281947/3e2b7a56-c011-4079-a650-a6c577caafbe)

**Comment by TongDucThanhNam** [comment]
"I have updated the EFI for installer/EFI. Please try using it and see. I tried again and it entered the macOS Recovery GUI successfully. I have a friend who has the exact same machine as yours, but theirs is still working and running well. It's strange that you're encountering an error..."

**Comment by JavadRabe** [comment]
> "I have updated the EFI for installer/EFI. Please try using it and see. I tried again and it entered the macOS Recovery GUI successfully. I have a friend who has the exact same machine as yours, but theirs is still working and running well. It's strange that you're encountering an error..."


i tried that and not work !
What is the BIOS version of your friend's laptop?  Mine is "HHCN32WW"

**Comment by TongDucThanhNam** [comment]
It's HHCN24WW. Maybe need check ssd nvme use AHCI (in Advanced bios); maybe need switch to Dynamic graphic mode. 
![368441686_654374429954516_1821612160315141712_n](https://github.com/TongDucThanhNam/OptimizeLegion5-15ACH6H/assets/96881214/26982619-4a85-4649-a590-d4de148042e0)

**Comment by JavadRabe** [comment]
I checked everything! There are only two differences, probably the BIOS version of my laptop does not allow macOS to boot or there is a problem in the order of the laptop disks! As you can see in the previous photos, Windows is installed on disk number 1 instead of number 0 , maybe this is the problem
